apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linto-live.fullname" . }}-secrets
  labels:
    {{- include "linto-live.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | default (randAlphaNum 16) | quote }}
  crypt-key: {{ .Values.sessionApi.env.SECURITY_CRYPT_KEY | default (randAlphaNum 32) | quote }}
