{{- if .Values.sessionApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-live.fullname" . }}-session-api
  labels:
    {{- include "linto-live.labels" . | nindent 4 }}
    app.kubernetes.io/component: session-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.sessionApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "linto-live.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: session-api
{{- end }}
---
{{- if .Values.sessionTranscriber.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-live.fullname" . }}-session-transcriber
  labels:
    {{- include "linto-live.labels" . | nindent 4 }}
    app.kubernetes.io/component: session-transcriber
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.sessionTranscriber.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.sessionTranscriber.service.srtPort }}
      targetPort: srt
      protocol: UDP
      name: srt
    - port: {{ .Values.sessionTranscriber.service.rtmpPort }}
      targetPort: rtmp
      protocol: TCP
      name: rtmp
  selector:
    {{- include "linto-live.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: session-transcriber
{{- end }}
---
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-live.fullname" . }}-postgres
  labels:
    {{- include "linto-live.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "linto-live.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
---
{{- if .Values.broker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-live.fullname" . }}-broker
  labels:
    {{- include "linto-live.labels" . | nindent 4 }}
    app.kubernetes.io/component: broker
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.broker.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    {{- include "linto-live.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: broker
{{- end }}
