apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linto-stt.fullname" . }}-secrets
  labels:
    {{- include "linto-stt.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.password | default (randAlphaNum 16) | quote }}
