{{- if .Values.whisper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-stt.fullname" . }}-whisper
  labels:
    {{- include "linto-stt.labels" . | nindent 4 }}
    app.kubernetes.io/component: whisper
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.whisper.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "linto-stt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: whisper
{{- end }}
---
{{- /* Diarization is a Celery worker, no K8s service needed */}}
---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-stt.fullname" . }}-redis
  labels:
    {{- include "linto-stt.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "linto-stt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
---
{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-stt.fullname" . }}-mongodb
  labels:
    {{- include "linto-stt.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "linto-stt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
---
{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-stt.fullname" . }}-api-gateway
  labels:
    {{- include "linto-stt.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "linto-stt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
{{- end }}
