apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linto-studio.fullname" . }}-secrets
  labels:
    {{- include "linto-studio.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.studioApi.env.CM_JWT_SECRET | default (randAlphaNum 32) | quote }}
  jwt-refresh-secret: {{ .Values.studioApi.env.CM_REFRESH_SECRET | default (randAlphaNum 32) | quote }}
  admin-email: {{ .Values.studioApi.env.SUPER_ADMIN_EMAIL | quote }}
  admin-password: {{ .Values.studioApi.env.SUPER_ADMIN_PWD | default (randAlphaNum 16) | quote }}
  {{- if .Values.studioApi.secrets.SMTP_PSWD }}
  smtp-password: {{ .Values.studioApi.secrets.SMTP_PSWD | quote }}
  {{- end }}
  {{- if .Values.studioApi.secrets.GOOGLE_CLIENT_SECRET }}
  google-client-secret: {{ .Values.studioApi.secrets.GOOGLE_CLIENT_SECRET | quote }}
  {{- end }}
  {{- if .Values.studioApi.secrets.GITHUB_CLIENT_SECRET }}
  github-client-secret: {{ .Values.studioApi.secrets.GITHUB_CLIENT_SECRET | quote }}
  {{- end }}
  {{- if .Values.studioApi.secrets.OIDC_CLIENT_SECRET }}
  oidc-client-secret: {{ .Values.studioApi.secrets.OIDC_CLIENT_SECRET | quote }}
  {{- end }}
