{{- if .Values.llmGatewayApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-llm.fullname" . }}-llm-api
  labels:
    {{- include "linto-llm.labels" . | nindent 4 }}
    app.kubernetes.io/component: llm-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.llmGatewayApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "linto-llm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: llm-api
{{- end }}
---
{{- if .Values.llmGatewayFrontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-llm.fullname" . }}-llm-frontend
  labels:
    {{- include "linto-llm.labels" . | nindent 4 }}
    app.kubernetes.io/component: llm-frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.llmGatewayFrontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "linto-llm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: llm-frontend
{{- end }}
---
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-llm.fullname" . }}-postgres
  labels:
    {{- include "linto-llm.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "linto-llm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-llm.fullname" . }}-redis
  labels:
    {{- include "linto-llm.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "linto-llm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
---
{{- if .Values.vllm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linto-llm.fullname" . }}-vllm
  labels:
    {{- include "linto-llm.labels" . | nindent 4 }}
    app.kubernetes.io/component: vllm
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.vllm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "linto-llm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: vllm
{{- end }}
